name: test
on:
  pull_request:

jobs:
  static-checks:
    name: 'Static test checks'
    runs-on: ubuntu-20.04
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
